# Generated by Django 5.0 on 2024-01-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapps', '0009_alter_booking_rating_alter_booking_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Total_cost',
            field=models.CharField(max_length=2505, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='no_of_days',
            field=models.IntegerField(null=True),
        ),
    ]
