# Generated by Django 5.0 on 2024-01-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapps', '0010_alter_booking_total_cost_alter_booking_no_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Total_cost',
            field=models.IntegerField(max_length=2505, null=True),
        ),
    ]
