# Generated by Django 5.0 on 2024-01-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapps', '0011_alter_booking_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Total_cost',
            field=models.IntegerField(null=True),
        ),
    ]
