# Generated by Django 5.0 on 2024-01-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapps', '0014_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='user_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
